pull_request_rules:
  - name: Merge on review approval
    conditions:
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      - -label~=(WIP|do-not-merge)
      - -title~=(WIP|wip)
    actions:
      merge:
        method: squash
        strict: smart
        strict_method: merge
        commit_message: title+body
